"use client";

import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { PageHeader } from "@/components/dashboard/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Field, Input } from "@/components/ui/field";
import { apiFetch } from "@/lib/api";

type Me={email:string;role:string;profile?:{full_name:string}};type Firm={name:string;slug:string};
export default function SettingsPage(){const [me,setMe]=useState<Me|null>(null);const [firm,setFirm]=useState<Firm|null>(null);const [name,setName]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>{Promise.all([apiFetch<Me>("/users/me"),apiFetch<Firm>("/firms/current")]).then(([u,f])=>{setMe(u);setFirm(f);setName(u.profile?.full_name||"")}).catch(e=>toast.error(e.message))},[]);async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await apiFetch("/users/me",{method:"PATCH",body:JSON.stringify({full_name:name})});toast.success("Profile updated")}catch(error){toast.error(error instanceof Error?error.message:"Update failed")}finally{setBusy(false)}}return <><PageHeader eyebrow="WORKSPACE SETTINGS" title="Profile and firm" description="Basic prototype settings for the authenticated CA user."/><div className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="font-bold">Your profile</h2><form onSubmit={save} className="mt-5 grid gap-4"><Field label="Full name"><Input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Email"><Input value={me?.email||""} disabled/></Field><Field label="Role"><Input value={me?.role||""} disabled/></Field><Button disabled={busy}>{busy?"Saving…":"Save profile"}</Button></form></Card><Card className="p-6"><h2 className="font-bold">Firm</h2><dl className="mt-5 grid gap-4 text-sm"><div className="flex justify-between border-b border-[#eeeae6] pb-3"><dt className="text-[#77716e]">Name</dt><dd className="font-semibold">{firm?.name||"—"}</dd></div><div className="flex justify-between border-b border-[#eeeae6] pb-3"><dt className="text-[#77716e]">Workspace slug</dt><dd className="font-semibold">{firm?.slug||"—"}</dd></div><div className="flex justify-between border-b border-[#eeeae6] pb-3"><dt className="text-[#77716e]">Data mode</dt><dd className="font-semibold">Synthetic prototype</dd></div></dl><p className="mt-6 rounded-xl bg-[#f8f7f5] p-3 text-xs leading-5 text-[#6b6562]">Firm-member and production onboarding flows are intentionally lightweight in this hiring prototype.</p></Card></div></>}
