import csv
import io
import zipfile

import fitz

from app.services import reports
from app.services.reports import (
    generate_document_manifest_csv,
    generate_readiness_pdf,
    generate_reconciliation_csv,
    generate_reconciliation_pdf,
    generate_validation_csv,
)


def _pdf_text(content: bytes) -> str:
    document = fitz.open(stream=content, filetype="pdf")
    return "\n".join(page.get_text() for page in document)


def test_generate_readiness_pdf_returns_pdf_bytes() -> None:
    summary = {
        "client": {
            "business_name": "Raj Traders",
            "legal_name": "Raj Traders",
            "gstin": "27RAJTR1234A1Z5",
            "filing_frequency": "monthly",
        },
        "application": {
            "id": "app-1",
            "period_label": "April 2026",
            "financial_year": "2026-27",
            "status": "ready_for_filing",
        },
        "firm": {"name": "Sharma & Associates"},
        "generated_at": "2026-08-23T12:00:00+00:00",
        "documents": {"required": 6, "received": 6, "reviewed": 6, "requirements": []},
        "document_manifest": [],
        "sales": {
            "invoice_count": 2,
            "taxable_value": 1000,
            "cgst": 90,
            "sgst": 90,
            "igst": 0,
            "cess": 0,
            "tax_total": 180,
            "invoice_total": 1180,
        },
        "purchases": {
            "invoice_count": 2,
            "taxable_value": 500,
            "cgst": 45,
            "sgst": 45,
            "igst": 0,
            "cess": 0,
            "tax_total": 90,
            "invoice_total": 590,
        },
        "validation": {
            "finding_count": 1,
            "reviewed_count": 1,
            "resolved_count": 1,
            "progress_percent": 100,
            "findings": [],
        },
        "reconciliation": {"status": "not_started", "summary": {}, "review_percent": 0},
        "alerts": [],
        "readiness": {"ready_for_filing": True, "ready_for_filing_percent": 100},
        "disclaimer": "GST preparation report generated by OBLIQ for CA review.",
    }
    content = generate_readiness_pdf(summary)
    assert content.startswith(b"%PDF")
    assert len(content) > 500
    text = _pdf_text(content)
    assert "GST Readiness Preparatory Report" in text
    assert "Ready for Filing" in text
    assert "Not performed / Separate optional review" in text
    assert "not a filed GST return" in " ".join(text.split())


def test_report_csvs_are_structured_and_ground_truth_is_excluded() -> None:
    manifest = generate_document_manifest_csv(
        [
            {
                "document_id": "business",
                "category": "Sales Register",
                "original_name": "Sales.xlsx",
                "source": "secure_link",
                "uploaded_at": "2026-08-23",
                "status": "approved",
            },
            {
                "document_id": "ground",
                "category": "Developer Ground Truth",
                "document_type": "developer_ground_truth",
                "original_name": "00_Set_Index_and_Ground_Truth.pdf",
                "source": "secure_link",
                "uploaded_at": "2026-08-23",
                "status": "excluded_reference",
            },
        ]
    )
    rows = list(csv.DictReader(io.StringIO(manifest.decode("utf-8-sig"))))
    assert [row["document_id"] for row in rows] == ["business"]

    validation = generate_validation_csv(
        [
            {
                "message": "GSTIN missing",
                "status": "resolved",
                "invoice_number": "P-1",
                "resolution": "Reviewed",
            }
        ]
    )
    assert "GSTIN missing" in validation.decode("utf-8-sig")


def test_reconciliation_report_contains_exact_evidence() -> None:
    item = {
        "id": "item-1",
        "match_status": "value_mismatch",
        "review_status": "reviewed",
        "evidence": {
            "books": {
                "supplier_gstin": "27ABCDE1234F1Z5",
                "invoice_number": "EFI/0826/889",
                "taxable_value": "90000",
                "cgst": "8100",
                "sgst": "8100",
            },
            "gstr2b": {
                "supplier_gstin": "27ABCDE1234F1Z5",
                "invoice_number": "EFI/0826/889",
                "taxable_value": "95000",
                "cgst": "8550",
                "sgst": "8550",
            },
            "difference_fields": ["taxable_value", "cgst", "sgst"],
        },
    }
    summary = {
        "client": {"business_name": "Raj Traders", "gstin": "27RAJTR1234A1Z5"},
        "application": {"period_label": "April 2026", "financial_year": "2026-27"},
        "firm": {"name": "Sharma & Associates"},
        "generated_at": "2026-08-23T12:00:00+00:00",
        "reconciliation": {"summary": {"value_mismatch": 1}, "review_percent": 100},
        "reconciliation_items": [item],
        "alerts": [],
    }
    content = generate_reconciliation_pdf(summary)
    text = _pdf_text(content)
    assert "GSTR-2B Reconciliation Working Report" in text
    assert "EFI/0826/889" in text
    assert "90,000" in text
    assert "95,000" in text
    assert "Final ITC treatment" in text
    csv_content = generate_reconciliation_csv([item]).decode("utf-8-sig")
    assert "books_taxable_value" in csv_content
    assert "90000" in csv_content


def test_export_archive_contains_each_generated_report_once() -> None:
    assert hasattr(reports, "generate_export_archive")
    content = reports.generate_export_archive(
        {
            "GST_Readiness_Preparatory_Report.pdf": b"pdf",
            "Document_Manifest.csv": b"manifest",
        }
    )
    with zipfile.ZipFile(io.BytesIO(content)) as archive:
        assert archive.namelist() == [
            "GST_Readiness_Preparatory_Report.pdf",
            "Document_Manifest.csv",
        ]
        assert archive.read("GST_Readiness_Preparatory_Report.pdf") == b"pdf"
