"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ClipboardCheck, Download, FileText, MessageCircleMore, RefreshCw, Send, ShieldCheck, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AssistantPanel } from "@/components/assistant/assistant-panel";
import { PageHeader } from "@/components/dashboard/page-header";
import { DocumentPanel } from "@/components/documents/document-panel";
import { FindingsPanel } from "@/components/documents/findings-panel";
import { ReconciliationPanel } from "@/components/reconciliation/reconciliation-panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/field";
import { Loading } from "@/components/ui/loading";
import { LiveWhatsAppDemoLink } from "@/components/whatsapp/live-whatsapp-demo-link";
import { apiFetch, resolveAssetUrl } from "@/lib/api";
import { formatCurrency, formatDate, formatStatus } from "@/lib/format";
import type { AuditEvent, GSTApplication, Reminder, Requirement } from "@/lib/types";

type Readiness={client:{business_name:string;gstin:string};application:GSTApplication;documents:{required:number;received:number;reviewed:number;missing_labels:string[]};sales:{invoice_count:number;taxable_value:number;tax_total:number};purchases:{invoice_count:number;taxable_value:number;tax_total:number};output_tax:number;potential_input_tax:number;estimated_liability:number;reconciliation:Record<string,number>;open_issues:{id:string;message:string}[];approval_status:string;readiness_status:string;disclaimer:string};
type Tab="overview"|"documents"|"validation"|"reconciliation"|"assistant"|"audit";
const tabs:[Tab,string][]=[["overview","Overview"],["documents","Documents & Extraction"],["validation","Validation"],["reconciliation","GSTR-2B Reconciliation"],["assistant","RAG Assistant"],["audit","Audit Trail"]];
const stages=["documents_requested","partially_received","extraction_review","validation_review","reconciliation_review","ready_for_ca_review","ready_for_filing"];

export default function ApplicationWorkspace(){
  const {applicationId}=useParams<{applicationId:string}>(); const [app,setApp]=useState<GSTApplication|null>(null); const [checklist,setChecklist]=useState<Requirement[]>([]);const [readiness,setReadiness]=useState<Readiness|null>(null);const [audit,setAudit]=useState<AuditEvent[]>([]);const [tab,setTab]=useState<Tab>("overview");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [draft,setDraft]=useState<Reminder|null>(null);const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const [a,c,r,events]=await Promise.all([apiFetch<GSTApplication>(`/applications/${applicationId}`),apiFetch<Requirement[]>(`/applications/${applicationId}/checklist`),apiFetch<Readiness>(`/applications/${applicationId}/readiness-summary`),apiFetch<AuditEvent[]>(`/applications/${applicationId}/audit`)]);setApp(a);setChecklist(c);setReadiness(r);setAudit(events);},[applicationId]);
  useEffect(()=>{load().catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[load]);
  const received=checklist.filter(item=>item.status!=="missing").length;const progress=checklist.length?Math.round(received/checklist.length*100):0;const currentStage=Math.max(0,stages.indexOf(app?.status||""));
  async function createDraft(kind:"request"|"reminder"){setBusy(true);try{const path=kind==="request"?`/applications/${applicationId}/document-request/draft`:`/applications/${applicationId}/reminders/draft`;const result=await apiFetch<Reminder>(path,{method:"POST"});setDraft(result);setMessage(result.draft_message);toast.success(kind==="request"?"Document request drafted":"Reminder drafted");}catch(error){toast.error(error instanceof Error?error.message:"Unable to draft message")}finally{setBusy(false)}}
  async function approveSend(){if(!draft)return;setBusy(true);try{const initial=(draft as unknown as {reminder_type?:string}).reminder_type==="initial_document_request";const path=initial?`/applications/${applicationId}/document-request/approve-send`:`/reminders/${draft.id}/approve-send`;await apiFetch(path,{method:"POST",body:JSON.stringify({reminder_id:draft.id,message})});toast.success("Approved message sent through the configured provider");setDraft(null);await load();}catch(error){toast.error(error instanceof Error?error.message:"Message failed")}finally{setBusy(false)}}
  async function exportFiles(){setBusy(true);try{const files=await apiFetch<Record<string,string>>(`/applications/${applicationId}/export`,{method:"POST"});Object.entries(files).forEach(([name,url],index)=>setTimeout(()=>{const link=document.createElement("a");link.href=resolveAssetUrl(url);link.download=name;link.target="_blank";link.click()},index*300));toast.success("Readiness package generated");await load();}catch(error){toast.error(error instanceof Error?error.message:"Export failed")}finally{setBusy(false)}}
  async function approveApplication(){setBusy(true);try{await apiFetch(`/applications/${applicationId}/approve`,{method:"POST"});toast.success("Application marked ready for filing");await load();}catch(error){toast.error(error instanceof Error?error.message:"Approval failed")}finally{setBusy(false)}}
  if(loading||!app||!readiness)return <Loading label="Opening GST workspace…"/>;
  return <>
    <PageHeader eyebrow="GST READINESS WORKSPACE" title={`${app.client?.business_name || "Client"} · ${app.period_label}`} description={`${app.client?.gstin} · Due ${formatDate(app.due_date)} · ${formatStatus(app.filing_frequency)} filing`} actions={<><Link href={`/dashboard/clients/${app.client_id}`} className="inline-flex items-center gap-2 rounded-full border border-[#dcd7d2] bg-white px-5 py-3 text-sm font-semibold"><ArrowLeft size={17}/>Client</Link><LiveWhatsAppDemoLink applicationId={applicationId}/><Button variant="secondary" onClick={exportFiles} disabled={busy}><Download size={17}/>Export pack</Button><Button onClick={approveApplication} disabled={busy}><ShieldCheck size={17}/>Approve readiness</Button></>}/>
    <Card className="mb-6 overflow-hidden"><div className="grid gap-5 bg-[#a4c5e5] p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-3"><Badge value={app.status}/><span className="text-xs font-semibold">{received} / {checklist.length} document categories received</span></div><div className="mt-4 h-2 max-w-xl overflow-hidden rounded-full bg-white/60"><div className="h-full rounded-full bg-[#191515] transition-all" style={{width:`${progress}%`}}/></div></div><div className="text-right"><strong className="text-3xl">{progress}%</strong><p className="text-xs">collection progress</p></div></div><div className="overflow-x-auto border-t border-[#eeeae6] bg-white p-4"><div className="flex min-w-[760px] items-center">{stages.map((stage,index)=><div key={stage} className="flex flex-1 items-center"><div className={`grid h-7 w-7 shrink-0 place-items-center rounded-full border text-xs font-bold ${index<=currentStage?"border-[#191515] bg-[#191515] text-white":"border-[#d9d4cf] bg-white text-[#8a8480]"}`}>{index<currentStage?<Check size={14}/>:index+1}</div><span className={`ml-2 text-[11px] font-semibold ${index<=currentStage?"text-[#191515]":"text-[#8a8480]"}`}>{formatStatus(stage)}</span>{index<stages.length-1&&<span className={`mx-3 h-px flex-1 ${index<currentStage?"bg-[#191515]":"bg-[#ded9d4]"}`}/>}</div>)}</div></div></Card>
    <div className="mb-6 flex gap-1 overflow-x-auto rounded-2xl border border-[#e5e2de] bg-white p-1">{tabs.map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold transition ${tab===value?"bg-[#191515] text-white":"text-[#6b6562] hover:bg-[#f5f3f0]"}`}>{label}</button>)}</div>
    {tab==="overview"&&<div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="grid gap-6"><Card className="p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-bold">Document checklist</h2><p className="mt-1 text-xs text-[#77716e]">OBLIQ compares required and received categories before processing.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>createDraft("request")} disabled={busy}><MessageCircleMore size={16}/>Draft request</Button><Button variant="secondary" onClick={()=>createDraft("reminder")} disabled={busy}><RefreshCw size={16}/>Draft reminder</Button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{checklist.map(item=><div key={item.id} className="flex items-center justify-between rounded-2xl border border-[#e5e2de] p-4"><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-full ${item.status==="missing"?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{item.status==="missing"?<FileText size={15}/>:<Check size={15}/>}</span><strong className="text-sm">{item.label}</strong></div><Badge value={item.status}/></div>)}</div></Card>
      <Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">GST readiness summary</h2><p className="mt-1 text-xs text-[#77716e]">Estimated from uploaded data and subject to CA review.</p></div><Badge value={readiness.readiness_status}/></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Sales invoices",readiness.sales.invoice_count],["Purchase invoices",readiness.purchases.invoice_count],["Open issues",readiness.open_issues.length]].map(([label,value])=><div key={label} className="rounded-2xl bg-[#f8f7f5] p-4"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-[#77716e]">{label}</p></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Output tax",readiness.output_tax],["Potential input tax",readiness.potential_input_tax],["Estimated liability",readiness.estimated_liability]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[#e5e2de] p-4"><p className="text-lg font-bold">{formatCurrency(value as number)}</p><p className="mt-1 text-xs text-[#77716e]">{label}</p></div>)}</div><p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">{readiness.disclaimer}</p></Card></div>
      <div className="grid content-start gap-6"><Card className="bg-[#191515] p-6 text-white"><Sparkles className="text-[#a4c5e5]"/><h2 className="mt-8 text-2xl font-bold tracking-[-.04em]">Ask before you decide.</h2><p className="mt-3 text-sm leading-6 text-white/65">Use the RAG assistant to explain a finding with application data and retrieved sources.</p><Button variant="secondary" className="mt-6" onClick={()=>setTab("assistant")}>Open assistant</Button></Card><Card className="p-5"><h2 className="font-bold">Open issues</h2><div className="mt-4 grid gap-3">{readiness.open_issues.slice(0,5).map(item=><div key={item.id} className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{item.message}</div>)}{!readiness.open_issues.length&&<div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">No unresolved validation findings.</div>}</div></Card><Card className="p-5"><h2 className="font-bold">Human approval gates</h2><ul className="mt-4 grid gap-3 text-sm text-[#625d5a]"><li className="flex gap-2"><ClipboardCheck size={17}/> Outbound messages wait for CA approval.</li><li className="flex gap-2"><ClipboardCheck size={17}/> Extracted data remains editable and reviewable.</li><li className="flex gap-2"><ClipboardCheck size={17}/> Filing occurs outside this prototype.</li></ul></Card></div></div>}
    {tab==="documents"&&<DocumentPanel applicationId={applicationId} checklist={checklist} onChanged={load}/>} {tab==="validation"&&<FindingsPanel applicationId={applicationId} onChanged={load}/>} {tab==="reconciliation"&&<ReconciliationPanel applicationId={applicationId} onChanged={load}/>} {tab==="assistant"&&<AssistantPanel applicationId={applicationId}/>} {tab==="audit"&&<Card className="overflow-hidden"><div className="border-b border-[#eeeae6] p-5"><h2 className="font-bold">Audit trail</h2><p className="mt-1 text-xs text-[#77716e]">Who did what, when, and against which workflow entity.</p></div><div className="divide-y divide-[#eeeae6]">{audit.map(event=><div key={event.id} className="grid gap-3 p-5 sm:grid-cols-[auto_1fr_auto]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8f1fa]"><FileText size={16}/></span><div><p className="text-sm font-semibold">{formatStatus(event.action.replaceAll(".","_"))}</p><p className="mt-1 text-xs text-[#77716e]">{event.entity_type} · {event.entity_id}</p></div><time className="text-xs text-[#77716e]">{formatDate(event.created_at)}</time></div>)}{!audit.length&&<div className="p-10 text-center text-sm text-[#77716e]">No audit events yet.</div>}</div></Card>}
    {draft&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4" onClick={()=>setDraft(null)}><Card className="w-full max-w-2xl p-6 shadow-2xl" onClick={(event)=>event.stopPropagation()}><p className="text-xs font-bold tracking-[.13em] text-[#477ca8]">HUMAN APPROVAL REQUIRED</p><h2 className="mt-3 text-2xl font-bold">Review WhatsApp message</h2><p className="mt-2 text-sm text-[#6b6562]">Edit the text before sending through the configured Vonage provider.</p><Textarea className="mt-5 h-56 w-full" value={message} onChange={e=>setMessage(e.target.value)}/><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="ghost" onClick={()=>setDraft(null)}>Cancel</Button><Button onClick={approveSend} disabled={busy}><Send size={16}/>{busy?"Sending…":"Approve & send"}</Button></div></Card></div>}
  </>;
}
