import Link from "next/link";
import {ArrowRight, Bot, Check, ShieldCheck} from "lucide-react";
import {LandingNavbar} from "@/components/landing/navbar";
import {DashboardPreview} from "@/components/landing/dashboard-preview";
import {AssistantSection, FeatureSections} from "@/components/landing/feature-section";

export default function HomePage() {
  return <main className="overflow-hidden">
    <LandingNavbar/>
    <section className="landing-hero-grid relative min-h-[760px] overflow-hidden bg-[var(--obliq-blue)] pb-20 pt-32 text-center text-[#191515] sm:min-h-[900px] sm:pb-24 sm:pt-40 dark:bg-[var(--obliq-canvas)] dark:text-[var(--obliq-ink)]">
      <div className="absolute -left-32 top-28 h-80 w-80 rounded-full bg-white/45 blur-3xl animate-pulse-soft"/><div className="absolute -right-24 top-8 h-96 w-96 rounded-full bg-[var(--obliq-warm)]/65 blur-3xl animate-pulse-soft"/>
      <div className="obliq-container relative">
        <div className="landing-reveal mx-auto inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/50 px-4 py-2 text-xs font-bold tracking-[.09em] dark:border-[var(--obliq-border)] dark:bg-[var(--obliq-surface)]"><Bot size={15}/> GST READINESS FOR INDIAN CA FIRMS</div>
        <h1 className="landing-reveal landing-delay-1 mx-auto mt-7 max-w-[940px] text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-7xl lg:text-[88px]">Automate GST. Review Confidently.</h1>
        <p className="landing-reveal landing-delay-2 mx-auto mt-7 max-w-2xl text-base leading-7 opacity-75 sm:text-lg">Collect, extract, validate, reconcile and prepare GST work in one workspace.</p>
        <div className="landing-reveal landing-delay-3 mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/auth/login" className="obliq-focus inline-flex items-center justify-center gap-2 rounded-full bg-[var(--obliq-action)] px-7 py-4 text-sm font-semibold text-[var(--obliq-action-ink)] transition hover:bg-[var(--obliq-action-hover)]">Sign in <ArrowRight size={17}/></Link><a href="#workflow" className="obliq-focus rounded-full border border-black/15 bg-white/45 px-7 py-4 text-sm font-semibold transition hover:bg-white/65 dark:border-[var(--obliq-border)] dark:bg-[var(--obliq-surface)] dark:hover:bg-[var(--obliq-interactive-hover)]">See the workflow</a></div>
        <DashboardPreview/>
      </div>
    </section>
    <section id="workflow" aria-label="OBLIQ GST readiness workflow" className="obliq-container py-20 text-center sm:py-24"><p className="text-xs font-bold tracking-[.16em] text-[var(--obliq-info-ink)]">FROM REQUEST TO WORKING</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-bold leading-[1.08] tracking-[-.045em] sm:text-5xl">A clear GST readiness flow.</h2><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{["Request", "Collect", "Extract", "Validate", "Reconcile", "Review", "Export"].map((label, index) => <div key={label} className="landing-reveal relative rounded-2xl border border-[var(--obliq-border)] bg-[var(--obliq-surface)] p-4 transition duration-300 hover:-translate-y-1 hover:border-[var(--obliq-blue-strong)] hover:shadow-[var(--obliq-shadow)]" style={{animationDelay: `${index * 70}ms`}}><span className="mx-auto grid h-7 w-7 place-items-center rounded-full bg-[var(--obliq-blue-soft)] text-xs font-bold text-[var(--obliq-info-ink)]">{index + 1}</span><p className="mt-3 text-sm font-semibold">{label}</p>{index < 6 && <ArrowRight className="absolute -right-2 top-1/2 hidden -translate-y-1/2 text-[var(--obliq-muted)] lg:block" size={14}/>}</div>)}</div><div className="mt-8 grid gap-3 text-left sm:grid-cols-3"><div className="rounded-2xl border border-[var(--obliq-border)] bg-[var(--obliq-surface-raised)] p-4"><strong className="text-sm">Private Supabase Storage</strong><p className="mt-1 text-xs leading-5 text-[var(--obliq-muted)]">Original GST files stay private and application-scoped.</p></div><div className="rounded-2xl border border-[var(--obliq-border)] bg-[var(--obliq-surface-raised)] p-4"><strong className="text-sm">Deterministic reconciliation</strong><p className="mt-1 text-xs leading-5 text-[var(--obliq-muted)]">Books and GSTR-2B differences remain exact and reviewable.</p></div><div className="rounded-2xl border border-[var(--obliq-border)] bg-[var(--obliq-surface-raised)] p-4"><strong className="text-sm">Application-scoped RAG</strong><p className="mt-1 text-xs leading-5 text-[var(--obliq-muted)]">Answers stay grounded in the GST workspace currently open.</p></div></div></section>
    <FeatureSections/>
    <AssistantSection/>
    <section id="control" className="obliq-container py-24"><div className="rounded-[36px] bg-[var(--obliq-warm)] p-8 sm:p-12"><div className="grid items-center gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-xs font-bold tracking-[.16em]">HUMAN CONTROL BY DESIGN</p><h2 className="mt-4 max-w-3xl text-4xl font-bold tracking-[-.045em] sm:text-5xl">AI assists. The CA controls.</h2></div><div className="grid gap-3 text-sm text-[var(--obliq-muted)]">{["Review extracted values", "Approve important findings", "Make final GST decisions"].map(item => <p key={item} className="flex items-center gap-2"><Check size={16} className="text-[var(--obliq-success-ink)]"/>{item}</p>)}<p className="mt-2 flex gap-2 text-xs leading-5"><ShieldCheck size={16} className="shrink-0"/>OBLIQ prepares GST working. It does not file returns or decide final ITC eligibility.</p></div></div></div></section>
    <footer className="border-t border-[var(--obliq-border)] bg-[var(--obliq-surface)] py-8"><div className="obliq-container flex flex-col justify-between gap-4 text-sm text-[var(--obliq-muted)] sm:flex-row"><strong className="text-[var(--obliq-ink)]">OBLIQ GST Readiness Copilot</strong><span>Prototype · Synthetic data only · Professional review required</span></div></footer>
  </main>;
}
