import { Check, FileSearch, MessageSquareText, ScanText, ShieldCheck } from "lucide-react";

const items = [
  { eyebrow: "ONE CONTROLLED WORKFLOW", title: "Collect the right GST documents without losing the audit trail.", text: "Start a monthly or quarterly GST period, generate its checklist, and let the CA approve every WhatsApp request and reminder before it is sent.", bullets: ["CA-approved WhatsApp messages", "Expiring secure upload links", "Missing-document detection"], visual: "collection" },
  { eyebrow: "DOCUMENT INTELLIGENCE", title: "Turn invoices and registers into structured, reviewable data.", text: "Use deterministic Excel and PDF parsers first, then AI for irregular scans. The original file remains beside extracted fields so the CA can approve or correct every result.", bullets: ["PDF, image, CSV and XLSX", "Field-level confidence", "Human correction history"], visual: "extraction" },
  { eyebrow: "GST READINESS", title: "Validate records and reconcile purchases with GSTR-2B.", text: "Flag format, date, arithmetic, period and duplicate issues. Match purchase-register rows against a simplified GSTR-2B file and show possible ITC differences for professional review.", bullets: ["Duplicate and wrong-period checks", "Invoice-level matching", "Readiness reports and exports"], visual: "reconciliation" },
];

function Visual({ type }: { type: string }) {
  if (type === "collection") return <div className="grid gap-3 p-5 sm:grid-cols-2"><div className="rounded-[20px] bg-[#f5f4f2] p-4"><div className="mb-4 flex items-center gap-2 text-sm font-semibold"><MessageSquareText size={17}/> WhatsApp request</div><div className="rounded-2xl rounded-tl-sm bg-[#dff3e5] p-3 text-xs leading-5">Hello Raj Traders, please upload your April GST documents using the secure link.</div></div><div className="rounded-[20px] bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-[#77716e]">DOCUMENT CHECKLIST</p>{["Sales register","Purchase register","Sales invoices","Purchase invoices","GSTR-2B"].map((x,i)=><div key={x} className="mt-3 flex items-center justify-between text-sm"><span>{x}</span><span className={i===1?"text-amber-700":"text-emerald-700"}>{i===1?"Missing":"Received"}</span></div>)}</div></div>;
  if (type === "extraction") return <div className="grid gap-3 p-5 sm:grid-cols-2"><div className="soft-grid min-h-64 rounded-[20px] bg-white p-5"><div className="rounded-xl border border-[#dcd7d2] bg-white p-4"><p className="text-xs font-bold">TAX INVOICE</p><div className="my-5 h-2 w-3/4 rounded bg-[#e5e2de]"/><div className="space-y-2">{[80,55,70,90,45].map((w,i)=><div key={i} style={{width:`${w}%`}} className="h-2 rounded bg-[#eeeae6]"/>)}</div></div></div><div className="rounded-[20px] bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2 text-sm font-semibold"><ScanText size={17}/> Extracted fields</div>{[["Supplier","Sharma Distributors"],["GSTIN","27ABCDE1234F1Z5"],["Invoice","SD-1042"],["Taxable value","₹50,000"],["Total","₹59,000"]].map(([k,v])=><div key={k} className="border-b border-[#eeeae6] py-2 text-xs"><span className="text-[#77716e]">{k}</span><strong className="float-right">{v}</strong></div>)}<div className="mt-4 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">94% extraction confidence</div></div></div>;
  return <div className="p-5"><div className="rounded-[20px] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-[#77716e]">PURCHASE REGISTER ↔ GSTR-2B</p><h3 className="mt-1 text-lg font-bold">150 invoices compared</h3></div><FileSearch size={28}/></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["140","Matched"],["7","Purchase only"],["4","GSTR-2B only"],["3","Amount mismatch"]].map(([v,k])=><div key={k} className="rounded-2xl bg-[#f7f5f2] p-3"><strong className="text-xl">{v}</strong><p className="mt-1 text-[11px] text-[#77716e]">{k}</p></div>)}</div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Possible ITC differences requiring CA review</div></div></div>;
}

export function FeatureSections() {
  return <section id="workflow" className="obliq-container space-y-24 py-28">{items.map((item,index)=><article id={index===1?"intelligence":undefined} key={item.title} className="grid items-center gap-10 lg:grid-cols-2"><div className={index%2?"lg:order-2":""}><p className="text-xs font-bold tracking-[.16em] text-[#477ca8]">{item.eyebrow}</p><h2 className="mt-4 max-w-xl text-4xl font-bold leading-[1.06] tracking-[-.045em] sm:text-5xl">{item.title}</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#625d5a]">{item.text}</p><div className="mt-7 grid gap-3">{item.bullets.map((bullet)=><div key={bullet} className="flex items-center gap-3 text-sm font-semibold"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#e8f1fa]"><Check size={15}/></span>{bullet}</div>)}</div></div><div className={`overflow-hidden rounded-[32px] ${index===1?"bg-[#f0e2d5]":"bg-[#a4c5e5]"} p-3 sm:p-7 ${index%2?"lg:order-1":""}`}><Visual type={item.visual}/></div></article>)}</section>;
}

export function AssistantSection() {
  return <section id="rag" className="bg-[#191515] py-28 text-white"><div className="obliq-container grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold tracking-[.16em] text-[#a4c5e5]">SOURCE-BACKED ASSISTANCE</p><h2 className="mt-4 text-4xl font-bold leading-[1.05] tracking-[-.045em] sm:text-5xl">Ask why something was flagged—not just what was flagged.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">The assistant combines structured client facts from PostgreSQL with retrieved GST guidance and firm SOPs from pgvector. Every guidance answer includes its source.</p></div><div className="rounded-[30px] bg-[#f8f7f5] p-5 text-[#191515] sm:p-8"><div className="rounded-2xl bg-[#e8f1fa] p-4 text-sm"><strong>CA:</strong> Why was invoice SD-1042 flagged?</div><div className="mt-3 rounded-2xl bg-white p-5 text-sm leading-6 shadow-sm"><div className="mb-3 flex items-center gap-2 font-semibold"><ShieldCheck size={18}/> OBLIQ assistant</div>The invoice total does not match the sum of the taxable value, CGST and SGST. Compare the extracted values with the original before approval.<div className="mt-4 rounded-xl border border-[#e5e2de] px-3 py-2 text-xs text-[#625d5a]">Source: GST Invoice Review SOP · Arithmetic checks</div></div></div></div></section>;
}
